[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = false

[rpc_endpoints]
base_sepolia = "https://sepolia.base.org"
# Or use your custom RPC:
# base_sepolia = "https://base-sepolia.g.alchemy.com/v2/YOUR_API_KEY"

[etherscan]
base_sepolia = { key = "${BASESCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }